### ISSUE TITLE
extension doesn't work

### ISSUE THREAD

**Issue by arisviel** [Defasium/vkCaptchaBreaker#10]
Both extensions don't work. I thought to use the model myself, but the directory("models/captcha_model.onnx") is empty

**Comment by arisviel** [comment]
I pulled the model out of the extension, launched it, it works. But there are suspicions about `background.js`, I don't think it was intended that way (:
![image](https://user-images.githubusercontent.com/55986619/126987175-7899c1fb-68b8-455e-829b-2d799a6f3515.png)

**Comment by Defasium** [comment]
> Both extensions don't work. I thought to use the model myself, but the directory("models/captcha_model.onnx") is empty

Please provide your device's specs, operating system and browser. What do you mean by "extensions don't work"?

Extension for chrome and firefox uses ONNX.js for model inference, the list of supported browsers can be found here: https://github.com/microsoft/onnxjs

**Comment by Defasium** [comment]
> I pulled the model out of the extension, launched it, it works. But there are suspicions about `background.js`, I don't think it was intended that way (:
> ![image](https://user-images.githubusercontent.com/55986619/126987175-7899c1fb-68b8-455e-829b-2d799a6f3515.png)

[ONNX.js library](https://www.npmjs.com/package/onnxjs) can't be easily used inside browser extensions.
Especially in the background script due to security problems. To make it possible the [browserify](https://browserify.org/) plugin is used which bundles and wraps all libraries inside one js file.
