### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by miztizm** [Defasium/vkCaptchaBreaker#18]
Установил
Включил (красным)
Начал добавлять друзей
Появилась капча vk.
Ничего не происходит и ошибок в консоли нету.
Должно автоматически резолвить или кликать надо куда то ?

-------
https://vk.com/friends
Win 11
Chrome Version 94.0.4606.81
Firefox 94.0.1 (64-bit)

**Comment by Defasium** [comment]
Only the mobile domain of the site (https://m.vk.com/*) is supported.
If you want me to add some new functionality that doesn't violate the terms of usage (https://vk.com/terms), please consider opening a new issue with an appropriate request.

**Comment by miztizm** [comment]
Забавно, а как будто бы данный плагин не нарушает terms of usage уже, мобильная или не мобильная.

**Comment by Defasium** [comment]
> Забавно, а как будто бы данный плагин не нарушает terms of usage уже, мобильная или не мобильная.

Нарушает использующий, в частности пункты 6.3.7 и 6.3.9. Пункт 6.3.7 ещё очень притянуто, нигде не описано, что является "нормальным функционированием Сайта". Пункт 6.3.9 нарушается, если использующий плагин не получил специальное разрешение от Администрации Сайта. Так что легально с некоторыми оговорками. За всё несёт ответственность использующий, а не само программное ПО (пункт 8.1, 9.3).

В качестве примера функционала, нарушающего https://vk.com/terms, можно привести пункты 6.3.6, 6.3.16, 7.1.2.
Такой функционал не планируется добавлять в новых релизах.

На этом вопрос считаю закрытым.

### The same in English
The terms are violated by the user, in particular paragraphs 6.3.7 and 6.3.9. Paragraph 6.3.7 is still very far-fetched, it is not described anywhere what is the "normal functioning of the Site". Clause 6.3.9 is violated if the user has not received special permission from the Site Administration. So it's legal with some caveats. The user is responsible for everything, not the software itself (clause 8.1, 9.3).

As an example of functionality that violates https://vk.com/terms , you can inspect paragraphs 6.3.6, 6.3.16, 7.1.2.
Such functionality is not planned to be added in new releases.

I think that's the end of the matter.
